### ISSUE TITLE
Бесконечный цикл при отсутствии/разрыве подключения

### ISSUE THREAD

**Issue by coldezzt** [prethink/PRTelegramBot#13]
Когда бот не может установить соединение с API он начинает бесконечно и очень быстро пытаться его установить/восстановить и из-за этого выводится огромное количество логов. Можно это как-то настроить?

Чтобы воспроизвести достаточно запустить бота без интернета.

**Comment by prethink** [comment]
Добавил параметр для ограничения спама в версии https://github.com/prethink/PRTelegramBot/releases/tag/v0.7.1

Теперь при создание нового бота, можно задать значение в минутах, которое будет ограничивать конкретно этот спам.
var telegram = new PRBotBuilder("Token").SetAntiSpamErrorMinute(10).Build()
