### ISSUE TITLE
Некорректно работает метод билдера бота .AddMiddlewares()

### ISSUE THREAD

**Issue by coldezzt** [prethink/PRTelegramBot#18]
При добавлении одной или нескольких мидлварей в пайплайн обработки запроса с помощью метода .AddMiddlewares(), в конечный проект добавляется только первая, то есть в сборке видно только первую.
Но при самом запросе, мидлваря не открывается и код внутри неё не запускается.

Создаю бота я вот так:
```cs
var bot = new PRBotBuilder(Configuration["Token"]!)
            .AddMiddlewares(new UpdateMiddleware())
            .SetClearUpdatesOnStart(true)
            .Build();
```

А мидлваря выглядит вот так:

```cs
public class UpdateMiddleware : MiddlewareBase
{
    private static int _value = 0;

    public override Task InvokeOnPreUpdateAsync(ITelegramBotClient bot, Update upd, Func<Task> next)
    {
        Console.WriteLine($"Hello! {_value}");
        base.InvokeOnPreUpdateAsync(bot, upd, next);
        return Task.CompletedTask;
    }
}
```

В чём может быть проблема? И как регистрировать сразу несколько мидлварей?

**Comment by prethink** [comment]
Привет, попробуй сделать как в примере
https://github.com/prethink/PRTelegramBot/blob/master/Examples/ConsoleExample/Middlewares/OneMiddleWare.cs

Там метод async и ничего не возвращает

**Comment by prethink** [comment]
Пример с регистрацией нескольких middleware

https://github.com/prethink/PRTelegramBot/blob/master/Examples/ConsoleExample/Program.cs
